### ISSUE TITLE
HecLib 6 and 7 don't work on the same thread together

### ISSUE THREAD

**Issue by dezidizon** [CVWRSM/cvwrsm#166]
This was originally reported by @hxiedwr in #163. 

HecLib 6 and 7 don't work on the same thread together, i.e. opening dvar (heclib 7) and svar (heclib 6) together on DSS perspective.

**Comment by rma-tom** [comment]
@hxiedwr -- I've created a branch and a pull request to address the problems with mixing DSS 6 and DSS 7 files.
I have seen different behavior with 6&7 files in the watchlists, running the models in debug mode, and I also noticed that values appear in schematics from DSS7 files, but not DSS6 files -- a thing I didn't expect at all.

I have a couple of questions for you:

1. Are there other places where you've seen one DSS type work but not the other? 
2. I expect that the changes to address these issues will be made in the class wrimsv2.evaluator.DssOperation. Are there other places you would suggest looking for opportunities to change DSS access?

**Comment by hxiedwr** [comment]
1. I reported all I found so far. 
2. One is DssOperation.java and the other is "DSSFileView.java" which I pointed in the Instruction.

**Comment by hxiedwr** [comment]
Actually it reminds me another file, which need to be looked into:

https://github.com/CentralValleyModeling/wrims/blob/Feature/wrims-devops/wrims-ide/src/main/java/wrimsv2_plugin/debugger/view/ProcessAltColumn.java

**Comment by rma-tom** [comment]
Excellent! Thank you very much.
I believe I'm making some progress by making the DssOperations.matchPathName functions work across differences between DSS7 and DSS6 paths, and I see that function call in the file you named.

**Comment by hxiedwr** [comment]
Good catch. That some functions in WRIMS 2 don't work for HecDss 6 and 7 together may be due to the fact that HecLib 6 uses "1MON" as timestep but HecLib 7 uses "1Month".

**Comment by rma-tom** [comment]
DSS7 paths can also be lower case, so I encountered mismatches between "c_kswck" and "C_KSWCK" as well as "1MON" vs. "1Month".

**Comment by hxiedwr** [comment]
Is there a flag to ignore case differences or all in upper case like HecLib 6 in HecLib 7? Otherwise, we have to work on converting dss to upper case for HecLib 7 output.

**Comment by rma-tom** [comment]
Yes. I'm working with Adam to rewrite the functions to take advantage of tools in newer DSS library.

**Comment by rma-tom** [comment]
The changes Adam and I made yesterday to the DssOperations.matchPathName functions made the Watch display work for both DSS6 and DSS7 in our quick in-house checks. The code changes are in PR #169

**Comment by hxiedwr** [comment]
Thanks for update.
