### ISSUE TITLE
wrims-core DVAlias write fails for DSS-7 output

### ISSUE THREAD

**Issue by rma-tom** [CVWRSM/cvwrsm#172]
Testing CalSim execution in devOps build with a DSS7 file as output produces this error 

java.lang.Exception: Unable to store record /CALSIM/dp_xcc025_72_pa/deep-percolation//1MON/L2020A/
Status: -534304000
  at hec.heclib.dss.HecDss.put(HecDss.java:366)
  at wrimsv2.evaluator.DssOperation.writeDVAliasToDSS(DssOperation.java:381)
  at wrimsv2.components.ControllerBatch.runModelCbc(ControllerBatch.java:1739)
  at wrimsv2.components.ControllerBatch.runModel(ControllerBatch.java:277)
  at wrimsv2.components.ControllerBatch.<init>(ControllerBatch.java:104)
  at wrimsv2.components.ControllerBatch.main(ControllerBatch.java:507)

I'm pretty sure this is caused by using "1MON" as the E-Part of a DSS 7 path in the "writeDVAliasToDSS" method.

**Comment by rma-tom** [comment]
@hxiedwr -- let me know if you want my help finding a solution for this.

**Comment by hxiedwr** [comment]
I am not sure what is the cause of this error. In the earlier version, HecDss7 can be written to dss without problem.

Also I think HecLib 7 should allow "1MON" in addition of "1Month" timestep for the backwards compatibilities of WRIMS and HecDss.

**Comment by rma-tom** [comment]
I may be mistaken about the error being due to "1MON" vs "1Month". I'll add myself to assignees and work on a repair.

**Comment by hxiedwr** [comment]
> @hxiedwr -- let me know if you want my help finding a solution for this.

I still stay with the master branch for urgent request. Once all the 7 issues we found are solved and tested, I will switch to DevOps. So please go ahead looking into this issue.

**Comment by rma-tom** [comment]
I have found that this error does not occur when the output is written to a new DSS-7 file, and only when writing to some -- but not all -- pre-existing DSS-7 files. The files that cause the problems do not appear to be corrupt, but this is not a reliably  reproduceable problem, and can be worked around by creating a new output file, so I'm going to close this issue without taking further action.

**Comment by rma-tom** [comment]
I'm reopening this issue because it occurred to me that it's most likely caused by a conflict between single-precision and double-precision. I'll check this idea and if I'm correct, I'll talk to Adam or Peter about addressing it. I'm pretty sure that this has come up in other DSS applications and there's a way to address it

**Comment by rma-tom** [comment]
@hxiedwr -- I examined the DSS files that caused the problem, and did some more tests. The write error was definitely caused by attempting to write results as double-precision time series (type 105) into an existing single-precision DSS record (type 100).

A similar issue has been seen in HEC-ResSim and addressed in heclib development. Recent versions of HECLIB allow writes to DSS to overwrite a single-precision DSS record with double-precision data -- but only if the DSS record contains no values. It won't replace an existing non-zero-length single-precision time series with a double-precision time series of the same name or store truncated double-precision vales in the existing single-precision record.

In its current state, the program writes all time-series data as double-precision, so I think that this error is unlikely to happen in actual use, and will become even less likely to happen as we go forward. The error messages that appear in the interface don't really describe the problem and its cause very well, so in the rare cases where users run into this, it could be very frustrating.

I see these as our options:
1. Do nothing -- this is unlikely to happen in the wild, and users can fix the problem by deleting their existing output files and re-running the model. They'll have to do that on their own initiative since the error messages don't guide them to a solution.
2. Catch the exception thrown by this particular issue and present a more informative message to the user.
3. Write additional code to clear the data from the existing DSS records and replace it with double-precision records. 

How would you like us to proceed?

**Comment by hxiedwr** [comment]
I think #2 would be my preference to ask users delete the single precision dss file.

**Comment by rma-tom** [comment]
@hxiedwr  -- I have some new information. The javaheclib.dll I tested yesterday was from a September build. If we move to the very latest DLL build, it resolves the single-precision/double-precision conflict and replaces type 100 records with type 105 records when new data is written. This is the same behavior that DSS6 produced when the same type conflict occurred.

In light of this, would you prefer to update to the latest DLL, which involves some risk, or proceed with the warning-message approach?

I should mention that this does not require changing the Java components of the HEC code

**Comment by hxiedwr** [comment]
I think it is good to use the new library to allow both single and double precision dss files.

**Comment by rma-tom** [comment]
@hxiedwr @jmdegeorge 
We'll proceed with the use of the new javaHecLib.dll -- https://www.hec.usace.army.mil/confluence/dssdocs/dsscprogrammer/release-notes

I believe that will not require any code changes in wrims-core.

**Comment by rma-tom** [comment]
Resolved with PR #175

**Comment by rma-tom** [comment]
closing
