### ISSUE TITLE
HecLib version 7 reading DSS files takes a significant amount of time

### ISSUE THREAD

**Issue by dezidizon** [CVWRSM/cvwrsm#52]
@hxiedwr reported that HecLib v7 takes a significant amount of time to read DSS data. 

Karl Tarbet is aware of this issue and is currently looking into the issue and resolving this.

**Comment by adamkorynta** [comment]
@hxiedwr - Karl produced a fixed to this in PR: https://github.com/HydrologicEngineeringCenter/hec-dss/pull/231, we should retest with the update.

**Comment by hxiedwr** [comment]
> @hxiedwr reported that HecLib v7 takes a significant amount of time to read DSS data.
> 
> Karl Tarbet is aware of this issue and is currently looking into the issue and resolving this.

Actually both unit test and cs3 run failed. I am not sure if I get the latest HecLib 7. I used gradle build to get the latest libraries.

Unit test with cache and HecTimeSeries read method only retrieved the data (Yuba_Tran timeseries) from 1920 to 2010. The actually data is from 1920 to 2015. 

Unit test with HecDss get retrieved the whole timeseries but this method is extremely slow when have CS3 runs.

I suspect that I didn't get the latest libraries after the fix.

**Comment by dezidizon** [comment]
@hxiedwr could you point us to the pull request for the gradle build to get the latest libraries? We'd like to verify the library versions that were pulled.

**Comment by hxiedwr** [comment]
I used the HecDss7 branch to pull the latest HecLib. If you prefer, you can merge the changes in HecDss 7 to WRIMS-DevOps. Then I will load the projects to Eclipse from different folders based on WIRMS-DevOps.

**Comment by adamkorynta** [comment]
@hxiedwr - my PR https://github.com/CentralValleyModeling/wrims/pull/57 has not merged into your branch. You can merge it, check out my pull request, or apply the update to the HecDss7 branch yourself for testing.

**Comment by hxiedwr** [comment]
I guess Tom is the 2nd reviewer. Tom, could you merge the Pull Request #57 to HecDSS7 after reviewing it?

**Comment by adamkorynta** [comment]
The PR is merged now, can you pull the latest and test again?

**Comment by hxiedwr** [comment]
Yes. I am doing it now. Thank you.

**Comment by hxiedwr** [comment]
The same problem after the pull request:
cache filter is fast, but miss some data in one timeseries.
HecDss get is able to retrieve all the data but very slow.

Again, I hope when RMA works with Army Corp, focus on cache filter method if possible. We have implemented this method in many different places in WRIMS. Also we need cache filter to speed up dss data reading.

**Comment by adamkorynta** [comment]
Can you point to the unit test that is failing? I believe Tom only provided me with the HecDss method.

**Comment by hxiedwr** [comment]
The function of test_readdss() in the Test_readdss class is the cache filter method I used in WRIMS 2. It was suggested by Peter at the beginning of the project. It is fast but misses the 2010-2015 data for the timeseries of "Yuba_Tran". I will share the dss file shortly.

test_readdss() function outputs number of data points in this timeseries and the unit test says 1081. But actually from 1920 to 2015, there should be 1140 data points.

**Comment by hxiedwr** [comment]
By the way, you might want to comment out test_readdss1 function. This function is for testing HecDss get. This method is very slow when integrated with WRIMS 2 because path name is not well filtered.

**Comment by adamkorynta** [comment]
Link: https://github.com/CentralValleyModeling/wrims/blob/Feature/HecDSS7/wrims_v2/wrims_v2/src/test/test_heclib7/Test_heclib7.java

**Comment by adamkorynta** [comment]
Running the test it looks like this is the catalog query that is causing the error and not the actual time series read. I will report to HEC.

**Comment by hxiedwr** [comment]
Sounds good.

The link for Test_readdss is

https://github.com/CentralValleyModeling/wrims/blob/Feature/HecDSS7/wrims_v2/wrims_v2/src/test/test_heclib7/Test_readdss.java

**Comment by adamkorynta** [comment]
Just to clarify: I'm seeing only 1130 data points in the HecDss.get() method, but only 1081 in the catalog equivalent

**Comment by hxiedwr** [comment]
Catalog filter shows starting date of the timesereis is Jan 1, 1920. On the other hand, HecDSS View shows the data from Oct 31, 1921 to Sep 30, 2015. I guess the data between Jan 1, 1920 to Sep 30, 1921 are null values.

If you count the data points from Oct 31, 1921 to Sep 30, 2015, it is 1130 which is consistent with HecDss get.

Catalog filter shows 1081 data points, which doesn't make sense. No matter counting from Jan 1, 1920 or Oct 31, 1921 to Sep 30, 2015, 1081 is less than those values. What I see is, the data read in this method is from from Jan 1, 1920 to Dec 2009. Data beyond 2010 is missing. That is 1080 data point. Jan, 1 1920 may be considered as Dec 31, 1919 so that is 1081 points.

I know the source of the data is through an extension of hydrology from Oct 2009 to Sep 2015.

**Comment by adamkorynta** [comment]
@hxiedwr - I made a PR that fixes the issue (at least in the test), I also updated the code that uses it to narrow the access to the read.

After investigating the DSSVue code, I noticed that it used the CondensedReference to get the full time window. Without that code it just uses the D-Part time window only: https://github.com/CentralValleyModeling/wrims/pull/58/files#diff-d4d14dfaddda517bbd2be8d75993fe5ef6fba6e0a1f95835acac450bb53421ecR82

**Comment by hxiedwr** [comment]
Thanks. I will take a look.

**Comment by adamkorynta** [comment]
@hxiedwr this PR: https://github.com/CentralValleyModeling/wrims/pull/59 is for the HecDSS7 branch

**Comment by hxiedwr** [comment]
> @hxiedwr this PR: #59 is for the HecDSS7 branch

Thank you. Will test the code.

**Comment by hxiedwr** [comment]
> @hxiedwr this PR: #59 is for the HecDSS7 branch

By the way, should I pull the PR #59 head or PR #59 merge? Do you know what the differences between them?

**Comment by adamkorynta** [comment]
I wouldn't merge until you've reviewed and tested it. You can check out pull requests locally using the GitHub CLI: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by hxiedwr** [comment]
Got it. Thanks.

**Comment by hxiedwr** [comment]
Both dss reading and writing with HecLib 7 in both 6 and 7 format work after testing the functions with DCR, DCP, and LTO CS3 studies. Look into merge HecDss7 branch into WRIMS_DevOps branch.
